jobs:
  - name: test-runSh
    type: runSh
    steps:
      - IN: testintegrationwebhook
      - TASK:
        - script: echo "---integration typed resource---"
        - script: echo "int name ------->-"$TESTINTEGRATIONWEBHOOK_NAME
        - script: echo "webhookurl ------->-"$TESTINTEGRATIONWEBHOOK_INTEGRATION_WEBHOOKURL
    
